services:
  postgres:
    image: postgres:17
    hostname: postgres
    container_name: postgres-stregsystemet
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: stregsystemet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stregsystemet
  stregsystemet:
    build:
      dockerfile: Dockerfile
    container_name: stregsystemet
    depends_on:
      - postgres
    restart: "no"
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://stregsystemet:password@postgres/stregsystemet
