name: Nix Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# env is unneeded and unsupported as nix builds are pure, so the environment is discarded anyway

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build
        run: nix build