name: Rust

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://stregsystemet:password@localhost/stregsystemet

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: stregsystemet
          POSTGRES_PASSWORD: password
          POSTGRES_DB: stregsystemet
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install sqlx-cli --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
          cargo sqlx prepare --check

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --all-features --all-targets -- -Dwarnings
          workdir: ./${{ matrix.project }}
          fail_on_error: true

      - name: Check formatting
        run: cargo fmt --all -- --check
