name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://stregsystemet:password@localhost/stregsystemet

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: stregsystemet
          POSTGRES_PASSWORD: password
          POSTGRES_DB: stregsystemet
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install sqlx-cli --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
